name: Verify Maven build on develop branch

on:
  push:
    branches:
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # New config
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Maven verify
        run: mvn verify --file pom.xml
