# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - wgverwaltung

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: wgverwaltung  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AzureAppService_PublishProfile_ca79de3be900449da3ae5ec1d8d0253b }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # New config
    - uses: actions/setup-java@v1
      with:
        java-version: '14.0.1' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'

    - name: 'Deploy to GitHub Packages'
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/Mueller-Patrick -Dtoken=${{ secrets.GH_TOKEN }}